# config.yml
## python pl_train_ann.py --batch_size 64 --input_size 256 --train_dir '../data/cars/train' --test_dir '../data/cars/test' --resnet_scale '50' --max_epochs 128  --checkpoint_dir 'logs' --num_classes 196 --is_distributed  --is_transfer --mixed bf16
name_space: 'bkdsnn_aircraft'
batch_size: 12
input_size: 224
train_dir: '../data/aircraft/train'
test_dir: '../data/aircraft/test'
max_epochs: 50
checkpoint_dir: 'logs'
num_classes: 100
is_distributed: true
is_transfer: true
mixed: '16-mixed'
# stu_arch: 'ti'
stu_arch: 'm'
name: 'qkformer'
tea_arch: 'swin_base_patch4_window7_224'
pre_trained_tea_path: 'pre_trained_ann_model/swin_base_patch4_window7_224_aircraft.pth'
learning_rate: 0.0001
dataset: 'aircraft'
T: 4

# nohup python pl_train_erkd_snn.py  --print-yaml --config config/dogs/plt_bkdtrain_snn_aircraft.yml &
# nohup python pl_train_erkd_snn.py  --print-yaml --config config/cubs200/plt_erkdtrain_snn_cub.yml &
# nohup python pl_train_erkd_snn.py  --print-yaml --config config/aircraft/plt_erkdtrain_snn_aircraft.yml &