# config.yml
name_space: 'student_snn_cub'
batch_size: 32
input_size: 224
train_dir: '../data/cub/train'
test_dir: '../data/cub/test'
max_epochs: 50
checkpoint_dir: 'logs'
num_classes: 100
is_distributed: true
is_transfer: true
mixed: '16-mixed'
arch: 'ti'
dataset: 'cub'
T: 4
learning_rate: 0.0001